/*
 * Careers content is managed here so every careers page stays in sync.
 * To publish a role, add it to this array with status: "active".
 * To remove it from the public listings without deleting it, use status: "closed".
 */
window.RECKONER_JOBS = [
    {
        id: "audit-manager",
        title: "Audit Manager",
        department: "Audit & Assurance",
        location: "Islamabad, Pakistan",
        jobType: "Full-time",
        experienceLevel: "Senior Level",
        experienceRequired: "5–7 Years",
        summary: "Lead complex audit engagements, manage client relationships and develop high-performing audit teams.",
        about: "We are seeking an experienced Audit Manager to lead a portfolio of assurance engagements. You will combine technical judgement, commercial awareness and confident leadership to deliver work our clients can trust.",
        responsibilities: ["Lead audit planning, fieldwork and completion across a varied client portfolio", "Review audit files and resolve complex accounting or assurance matters", "Manage engagement budgets, timelines and client communications", "Coach assistant managers, seniors and trainees", "Support proposals, tenders and the continued growth of the audit practice"],
        requirements: ["Relevant degree in Accounting, Finance or a related field", "ACA, ACCA, CA or equivalent professional qualification", "5–7 years of external audit experience", "Strong knowledge of auditing standards and financial reporting", "Proven people leadership and client relationship skills"],
        qualifications: ["ACA, ACCA, CA or an equivalent recognised qualification", "Current knowledge of audit and financial reporting requirements"],
        benefits: ["Professional Development", "Learning & Training", "Career Growth", "Collaborative Environment", "Exposure to Diverse Clients", "Mentorship & Support"],
        deadline: "30 October 2026",
        status: "active"
    },
    {
        id: "assistant-audit-manager",
        title: "Assistant Audit Manager",
        department: "Audit & Assurance",
        location: "Islamabad, Pakistan",
        jobType: "Full-time",
        experienceLevel: "Mid Level",
        experienceRequired: "3–5 Years",
        summary: "Coordinate audit assignments, review fieldwork and help teams deliver rigorous, timely engagements.",
        about: "Join our Audit & Assurance team as an Assistant Audit Manager, taking ownership of day-to-day engagement delivery while supporting managers and developing junior colleagues.",
        responsibilities: ["Coordinate audit planning and fieldwork", "Review working papers and financial statements", "Track engagement progress, budgets and key risks", "Maintain clear communication with clients", "Coach senior and junior audit team members"],
        requirements: ["Relevant Accounting or Finance degree", "Professional qualification or advanced progress toward qualification", "3–5 years of external audit experience", "Sound technical and analytical skills", "Strong organisation and communication"],
        qualifications: ["ACCA, ACA, CA or equivalent qualification/progress", "Relevant audit methodology training"],
        benefits: ["Professional Development", "Learning & Training", "Career Growth", "Collaborative Environment", "Exposure to Diverse Clients", "Mentorship & Support"],
        deadline: "30 October 2026",
        status: "active"
    },
    {
        id: "senior-auditor",
        title: "Senior Auditor",
        department: "Audit & Assurance",
        location: "Islamabad, Pakistan",
        jobType: "Full-time",
        experienceLevel: "Mid Level",
        experienceRequired: "2–4 Years",
        summary: "Lead audit fieldwork, supervise junior team members and contribute to high-quality audit engagements.",
        about: "We are looking for a motivated Senior Auditor to join our Audit & Assurance team. The successful candidate will play an important role in delivering high-quality audit engagements, working directly with clients and supporting junior team members.",
        responsibilities: ["Plan and perform audit procedures", "Prepare and review audit working papers", "Analyse financial statements and supporting documentation", "Identify and assess audit risks", "Communicate with clients throughout the engagement", "Supervise and support junior team members", "Assist in preparing audit reports and management recommendations"],
        requirements: ["Relevant degree in Accounting, Finance or related field", "Relevant professional qualification or progress toward qualification", "2–4 years of audit experience", "Strong understanding of auditing and financial reporting", "Good analytical and communication skills", "Ability to manage multiple assignments and deadlines"],
        qualifications: ["ACCA, ACA, CA or equivalent qualification/progress", "Practical external audit experience"],
        benefits: ["Professional Development", "Learning & Training", "Career Growth", "Collaborative Environment", "Exposure to Diverse Clients", "Mentorship & Support"],
        deadline: "15 October 2026",
        status: "active"
    },
    {
        id: "audit-associate",
        title: "Audit Associate",
        department: "Audit & Assurance",
        location: "Islamabad, Pakistan",
        jobType: "Full-time",
        experienceLevel: "Entry Level",
        experienceRequired: "0–2 Years",
        summary: "Support assurance assignments, build strong audit fundamentals and work closely with experienced colleagues.",
        about: "This role is an opportunity to develop a strong grounding in external audit while contributing to well-managed engagements across a diverse client base.",
        responsibilities: ["Perform assigned audit tests and document results", "Prepare clear and complete working papers", "Reconcile financial data and supporting records", "Raise questions and exceptions promptly", "Participate in client and team status meetings"],
        requirements: ["Degree in Accounting, Finance or a related discipline", "Interest in pursuing a professional qualification", "Strong attention to detail", "Confident written and verbal communication", "Ability to learn quickly and work collaboratively"],
        qualifications: ["Graduate or part-qualified ACCA, CA, ACA or equivalent", "Sound Microsoft Excel skills"],
        benefits: ["Professional Development", "Learning & Training", "Career Growth", "Collaborative Environment", "Exposure to Diverse Clients", "Mentorship & Support"],
        deadline: "15 November 2026",
        status: "active"
    },
    {
        id: "trainee-auditor",
        title: "Trainee Auditor",
        department: "Audit & Assurance",
        location: "Islamabad, Pakistan",
        jobType: "Internship",
        experienceLevel: "Entry Level",
        experienceRequired: "No prior experience",
        summary: "Begin your audit career with structured learning, practical assignments and support from experienced mentors.",
        about: "Our trainee programme gives ambitious graduates practical exposure to audit work, structured learning and close support as they begin a professional career.",
        responsibilities: ["Support audit testing and file preparation", "Organise and verify client documentation", "Learn the firm’s audit methodology and quality standards", "Attend team briefings and development sessions", "Complete assigned work accurately and on time"],
        requirements: ["Recent or expected degree in Accounting, Finance or related field", "Commitment to a professional accounting qualification", "Strong numeracy and attention to detail", "A responsible and curious approach to learning", "Clear communication and teamwork"],
        qualifications: ["Graduate, finalist or early-stage professional student", "No prior audit experience required"],
        benefits: ["Professional Development", "Learning & Training", "Career Growth", "Collaborative Environment", "Exposure to Diverse Clients", "Mentorship & Support"],
        deadline: "30 November 2026",
        status: "active"
    },
    {
        id: "tax-associate",
        title: "Tax Associate",
        department: "Tax & Advisory",
        location: "Islamabad, Pakistan",
        jobType: "Full-time",
        experienceLevel: "Entry Level",
        experienceRequired: "1–2 Years",
        summary: "Prepare tax computations, support compliance work and help clients navigate their reporting obligations.",
        about: "We are looking for a careful, commercially aware Tax Associate to support compliance and advisory assignments for businesses and individuals.",
        responsibilities: ["Prepare tax computations and supporting schedules", "Assist with returns, registrations and client correspondence", "Research tax matters and summarise findings", "Maintain accurate engagement records", "Support senior colleagues on advisory assignments"],
        requirements: ["Degree in Accounting, Finance, Tax or related field", "1–2 years of relevant tax experience", "Working knowledge of tax compliance", "Strong research and numerical skills", "Clear written communication"],
        qualifications: ["ACCA, CA, ACA, CTA or equivalent qualification/progress", "Relevant tax compliance experience"],
        benefits: ["Professional Development", "Learning & Training", "Career Growth", "Collaborative Environment", "Exposure to Diverse Clients", "Mentorship & Support"],
        deadline: "31 October 2026",
        status: "active"
    },
    {
        id: "advisory-associate",
        title: "Advisory Associate",
        department: "Tax & Advisory",
        location: "Islamabad, Pakistan",
        jobType: "Full-time",
        experienceLevel: "Mid Level",
        experienceRequired: "2–3 Years",
        summary: "Turn financial information into practical insight and support varied client advisory engagements.",
        about: "As an Advisory Associate, you will work with experienced professionals to analyse business information, solve practical problems and help clients make confident decisions.",
        responsibilities: ["Perform financial and commercial analysis", "Prepare client-ready reports and presentations", "Research industries, markets and regulations", "Support project planning and delivery", "Maintain proactive communication with clients and colleagues"],
        requirements: ["Degree in Accounting, Finance, Economics or related field", "2–3 years of relevant experience", "Strong analytical and problem-solving ability", "Advanced spreadsheet and presentation skills", "Professional judgement and attention to detail"],
        qualifications: ["Professional accounting or finance qualification/progress preferred", "Relevant analytical or advisory experience"],
        benefits: ["Professional Development", "Learning & Training", "Career Growth", "Collaborative Environment", "Exposure to Diverse Clients", "Mentorship & Support"],
        deadline: "15 November 2026",
        status: "active"
    },
    {
        id: "accounts-associate",
        title: "Accounts Associate",
        department: "Finance & Accounts",
        location: "Islamabad, Pakistan",
        jobType: "Full-time",
        experienceLevel: "Entry Level",
        experienceRequired: "1–2 Years",
        summary: "Prepare accurate accounts, maintain financial records and support reliable client reporting.",
        about: "Join our Finance & Accounts team to support accurate reporting, well-controlled records and responsive service for a varied portfolio of clients.",
        responsibilities: ["Prepare accounts and supporting schedules", "Maintain ledgers and complete reconciliations", "Assist with month-end reporting", "Resolve routine client queries", "Keep records complete, accurate and review-ready"],
        requirements: ["Degree in Accounting, Finance or related field", "1–2 years of accounts preparation experience", "Understanding of bookkeeping and financial statements", "Strong attention to detail", "Good organisation and client communication"],
        qualifications: ["ACCA, CA, ACA, CIMA or equivalent qualification/progress", "Proficiency in spreadsheets and accounting software"],
        benefits: ["Professional Development", "Learning & Training", "Career Growth", "Collaborative Environment", "Exposure to Diverse Clients", "Mentorship & Support"],
        deadline: "15 November 2026",
        status: "active"
    }
];
